# coding:utf-8

'''bug的定义'''
# 程序中出现的错误，但有没有通过异常去捕获，以至于直接抛出，导致程序的崩溃

a = 1
print(a)
b = 2
print(b)
c = 3
print(c)
d = 4
print(d)

def test1():
    print(5)

test1()